import json

data = """
[FAE](https://github.com/wearefine/fae/) 
[activeWorkflow](https://github.com/automaticmode/active_workflow) 
[adopt-a-hydrant](https://github.com/codeforamerica/adopt-a-hydrant) 
[airCasting](https://github.com/HabitatMap/AirCasting) 
[alaveteli](https://github.com/mysociety/alaveteli) 
[alonetone](https://github.com/sudara/alonetone) 
[api.rss](https://github.com/davidesantangelo/api.rss) 
[asakusaSatellite](https://github.com/codefirst/AsakusaSatellite) 
[askaway](https://github.com/askaway/askaway) 
[autolab](https://github.com/autolab/Autolab) 
[beatstream](https://github.com/Darep/Beatstream) 
[bike_index](https://github.com/bikeindex/bike_index) 
[blackCandy](https://github.com/blackcandy-org/black_candy) 
[brimir](https://github.com/ivaldi/brimir) 
[calagator](https://github.com/calagator/calagator) 
[campo](https://github.com/chloerei/campo) 
[canvas-lms](https://github.com/instructure/canvas-lms) 
[catarse](https://github.com/catarse/catarse) 
[chatwoot](https://github.com/chatwoot/chatwoot) 
[chronlife](https://github.com/maciejb2k/chronlife) 
[ciao](https://github.com/brotandgames/ciao) 
[coRM](https://github.com/SIGIRE/CoRM) 
[coderwall (legacy)](https://github.com/coderwall/coderwall
[coderwall (next)](https://github.com/coderwall/coderwall
[codetriage](https://github.com/codetriage/codetriage) 
[commudle](https://github.com/commudle/commudle) 
[contribulator](https://github.com/24pullrequests/contribulator) 
[coursemology2](https://github.com/Coursemology/coursemology2) 
[covoiturage-libre](https://github.com/covoiturage-libre/covoiturage-libre) 
[crabgrass-core](https://0xacab.org/liberate/crabgrass) 
[crowdAI](https://github.com/crowdAI/crowdai) 
[crowdtiltOpen](https://github.com/Crowdtilt/CrowdtiltOpen) 
[cw-ovp](https://github.com/x1wins/CW-OVP) 
[danbooru](https://github.com/danbooru/danbooru) 
[dcaf_case_management](https://github.com/DARIAEngineering/dcaf_case_management) 
[dgidb](https://github.com/dgidb/dgidb) 
[diaspora](https://github.com/diaspora/diaspora) 
[discourse](https://github.com/discourse/discourse) 
[docuseal](https://github.com/docusealco/docuseal) 
[ekylibre](https://github.com/ekylibre/ekylibre) 
[encrypt.to](https://github.com/encrypt-to/encrypt.to) 
[eol](https://github.com/EOL/deprecated_eol) 
[expertiza](https://github.com/expertiza/expertiza) 
[fairmondo](https://github.com/fairmondo/fairmondo) 
[fat-free-crm](https://github.com/fatfreecrm/fat_free_crm) 
[feedbin](https://github.com/feedbin/feedbin) 
[follow-all](https://github.com/codeforamerica/follow-all) 
[forem](https://github.com/forem/forem) 
[fromthepage](https://github.com/benwbrum/fromthepage) 
[gitlabhq](https://github.com/gitlabhq/gitlabhq) 
[graff_mags](https://github.com/dankleiman/graff_mags) 
[granny](https://github.com/roberthopman/granny) 
[growstuff](https://github.com/Growstuff/growstuff) 
[hackershare](https://github.com/hackershare/hackershare) 
[hashrobot](https://github.com/rysmith/hashrobot) 
[helpy](https://github.com/helpyio/helpy) 
[hitobito](https://github.com/hitobito/hitobito) 
[hours](https://github.com/defactosoftware/hours) 
[human-essentials](https://github.com/rubyforgood/human-essentials) 
[inaturalist](https://github.com/inaturalist/inaturalist) 
[intercityup.com](https://github.com/intercity/intercity-next) 
[kanban](https://github.com/seanomlor/kanban) 
[kitsu-tools](https://github.com/hummingbird-me/kitsu-tools) 
[lavish](https://github.com/mquan/lavish) 
[lifeToRemind](https://github.com/eduqg/LifeToRemind) 
[lobsters](https://github.com/lobsters/lobsters) 
[loomio](https://github.com/loomio/loomio) 
[mastodon](https://github.com/mastodon/mastodon) 
[multiwoven](https://github.com/Multiwoven/multiwoven)
[obl.ong](https://github.com/obl-ong/admin) 
[obtvse2](https://github.com/natew/obtvse2) 
[onebody](https://github.com/seven1m/onebody) 
[openFarm](https://github.com/openfarmcc/OpenFarm) 
[opencongress](https://github.com/sunlightlabs/opencongress) 
[openproject](https://github.com/opf/openproject) 
[opensourcefriday](https://github.com/github/opensourcefriday) 
[openstreetmap-website](https://github.com/openstreetmap/openstreetmap-website) 
[otwarchive](https://github.com/otwcode/otwarchive) 
[passwordPusher](https://github.com/pglombardo/PasswordPusher) 
[peatio](https://github.com/peatio/peatio) 
[planningalerts-app](https://github.com/openaustralia/planningalerts) 
[podiscover](https://github.com/enderahmetyurt/podiscover) 
[popHealth](https://github.com/pophealth/popHealth) 
[postal](https://github.com/postalserver/postal) 
[publify](https://github.com/publify/publify) 
[quant](https://github.com/jdjkelly/quant) 
[racing_on_rails](https://github.com/scottwillson/racing_on_rails) 
[rapidFTR](https://github.com/rapidftr/RapidFTR) 
[redmine](https://github.com/edavis10/redmine) 
[rentmybikes-rails](https://github.com/balanced/rentmybikes-rails) 
[reservations](https://github.com/YaleSTC/reservations) 
[retrospring](https://github.com/retrospring/retrospring) 
[rletters](https://codeberg.org/rletters/rletters) 
[rubygems.org](https://github.com/rubygems/rubygems.org) 
[sanataro](https://github.com/kaznum/sanataro) 
[scholarsphere](https://github.com/psu-libraries/scholarsphere) 
[selfstarter](https://github.com/apigy/selfstarter) 
[sharetribe](https://github.com/sharetribe/sharetribe) 
[socify](https://github.com/scaffeinate/socify) 
[somleng](https://github.com/somleng/somleng) 
[splits-io](https://github.com/glacials/splits-io) 
[spokenvote](https://github.com/Spokenvote/spokenvote) 
[stackneveroverflow](https://github.com/liaoziyang/stackneveroverflow) 
[teambox](https://github.com/redbooth/teambox) 
[theodinproject](https://github.com/TheOdinProject/theodinproject) 
[tracks](https://github.com/TracksApp/tracks) 
[trado](https://github.com/Jellyfishboy/trado) 
[vglist](https://github.com/connorshea/vglist) 
[websiteOne](https://github.com/AgileVentures/WebsiteOne) 
[whitehall](https://github.com/alphagov/whitehall)
"""

lines = data.strip().split("\n")

result = []
for line in lines:
    name = line.split(']')[0][1:]
    url = line.split('(')[1][:-1].replace(')', '')
    result.append({"name": name, "url": url})

json_data = json.dumps(result, indent=4)

# Save the json data to a file
output_file = './github_repos.json'
with open(output_file, 'w') as file:
    file.write(json_data)